version: '3.8'

services:
  # Base de datos para desarrollo
  postgres:
    image: postgres:15-alpine
    container_name: interview-ai-dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview_ai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para desarrollo
  redis:
    image: redis:7-alpine
    container_name: interview-ai-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

  # Adminer para gestión de BD (opcional)
  adminer:
    image: adminer:4
    container_name: interview-ai-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  default:
    name: interview-ai-dev-network